MODEA EQU 0X01

    ORG 0X00
    GOTO INICIO

    ORG 0X04

INT
    GOTO INT

INICIO
    BSF STATUS, RP0
    CLRF TRISB
    BCF STATUS, RP0

LOOP
    MOVLW 0x3f 
    MOVWF PORTB
    MOVLW 0x06
    MOVWF PORTB
    MOVLW 0x5b
    MOVWF PORTB
    MOVLW 0x4f
    MOVWF PORTB
    MOVLW 0x66
    MOVWF PORTB
    MOVLW 0x6d
    MOVWF PORTB
    MOVLW 0x7d
    MOVWF PORTB
    MOVLW 0x07
    MOVWF PORTB
    MOVLW 0x7f
    MOVWF PORTB
    MOVLW 0x6f
    MOVWF PORTB
    MOVLW 0x77
    MOVWF PORTB
    MOVLW 0x7c
    MOVWF PORTB
    MOVLW 0x39
    MOVWF PORTB
    MOVLW 0x5e
    MOVWF PORTB
    MOVLW 0x79
    MOVWF PORTB
    MOVLW 0x71
    MOVWF PORTB

    GOTO LOOP